version: '3.11'

services:
 api:
  container_name: remwatch_api
  build: .
  command: >
   /bin/sh -c "alembic upgrade head &&
   echo \"Starting Api Server\" &&
   uvicorn app.main:app --host 0.0.0.0 --port 8000"
  ports:
   - 8000:8000
  environment:
   - DB_CONFIG_FROM_ENV=True
   - POSTGRES_HOST=remwatch_postgres_db
   - POSTGRES_PORT=5432
   - POSTGRES_DB=remwatch
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=password
  depends_on:
   - database

 database:
  container_name: remwatch_postgres_db
  image: postgres
  ports:
   - 5432:5432
  restart: always
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=password
   - POSTGRES_DB=remwatch
  volumes:
   - pgdata:/var/lib/postgresql/data

volumes:
 pgdata: {}
