"""define relationship between user/series and watchlist

Revision ID: 004716abcedc
Revises: 90ab4250d9e5
Create Date: 2023-05-25 22:05:13.373054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004716abcedc'
down_revision = '90ab4250d9e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
