"""update series relationship to watchlist_series

Revision ID: 2d3638dd4daf
Revises: bf2afe5fd878
Create Date: 2023-05-25 23:14:02.300248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3638dd4daf'
down_revision = 'bf2afe5fd878'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
