"""add cascade delete

Revision ID: 3399cfc3540a
Revises: a95a778b08ac
Create Date: 2023-06-01 23:32:32.950914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3399cfc3540a'
down_revision = 'a95a778b08ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
