"""add title to watchlist table

Revision ID: 90ab4250d9e5
Revises: cc2eae58a560
Create Date: 2023-05-25 21:31:33.600704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ab4250d9e5'
down_revision = 'cc2eae58a560'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist', 'title')
    # ### end Alembic commands ###
