"""define relationship between user/series and watchlist

Revision ID: 945ca1c52ce6
Revises: 004716abcedc
Create Date: 2023-05-25 22:06:03.794156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945ca1c52ce6'
down_revision = '004716abcedc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
